on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 20 * * *'

name: generate-forecast

jobs:
  build:
    runs-on: ubuntu-latest
    container: eco4cast/usgsrc4cast-python:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate forecasts
        run: |
          python forecast_model.py
